spring:
  application:
    name: basic-sample-spring
  datasource:
    url: jdbc:mysql://db:3306/sample-db?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    username: user
    password: P@ssw0rd!
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    url: jdbc:mysql://db:3306/sample-db?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    user: user
    password: P@ssw0rd!
    baseline-on-migrate: true
    locations:
      - classpath:db/migration

  doma:
    dialect: mysql
    sql-file-repository: no-cache
    naming:
      entity: snake_lower_case
      column: snake_lower_case
  
  mail:
    host: mailhog
    port: 1025
    username: "sample"
    password: "password"
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      from: "noreply@sample.jp"
      register-link: "http://localhost:3000/register"

logging:
  level:
    org.seasar.doma: DEBUG
    org.flywaydb: INFO